### ISSUE TITLE
imdecode breaking when migrating from 2.0.0-dev.12 to 2.1.0-dev.0

### ISSUE THREAD

**Issue by MichelM279** [rainyl/opencv_dart#227]
**Describe the bug**

**To Reproduce**
Using pretty much the example code with minimal altercations (tested to work on 2.0.0-dev.12):

in main.dart:
```
final String path = img.path;
final Uint8List buffer = await File(path).readAsBytes();
final RecognitionResults recognizedResults = await recognitionStarter.recognize(buffer);
```

or with the same sample image as in the example:
```
final ByteData data = await DefaultAssetBundle.of(context).load('assets/images/lenna.png');
final Uint8List bytes = data.buffer.asUint8List();
final RecognitionResults recognizedResults = await recognitionStarter.recognize(bytes);
```

in recognitionStarter:
```
Future<RecognitionResults> recognize(final Uint8List buffer) async {
final cv.Mat im = cv.imdecode(buffer, cv.IMREAD_COLOR);
```
crashes at imdecode

**Expected behavior**
Image being decoded from uInt8List to cv.Mat

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CvException(code: -215, err: , msg:OpenCV(4.10.0) D:\a\opencv.full\opencv.full\build\opencv\modules\imgcodecs\src\loadsave.cpp:815: error: (-215:Assertion failed) buf.checkVector(1, CV_8U) > 0 in function 'cv::imdecode_'
) in cv::imdecode_ of file D:\a\opencv.full\opencv.full\build\opencv\modules\imgcodecs\src\loadsave.cpp:815
#0      throwIfFailed (package:opencv_dart/src/core/base.dart:74:5)
#1      cvRun (package:opencv_dart/src/core/base.dart:79:58)
#2      imdecode (package:opencv_dart/src/imgcodecs/imgcodecs.dart:92:3)
#3      RecognitionStarter.recognize (package:tcg_nexus_scanner/card-recognition/recognition-starter.dart:13:26)
#4      _MyAppState.build.<anonymous closure> (package:tcg_nexus_scanner/main.dart:82:91)
<asynchronous suspension>
```

**Comment by rainyl** [comment]
@MichelM279 Get it. Will test it.

**Comment by rainyl** [comment]
@MichelM279 Could you please update your `pubspec.yaml` to use opencv_dart from github repo to test whether this issue is solved by #228? Since I have no plan to release new versions for `v2.x` until they make `Native Assets` feature stable.

```yaml
  opencv_dart:
    git:
      url: https://github.com/rainyl/opencv_dart.git
      ref: c5b79c6
```

**Comment by MichelM279** [comment]
@rainyl thank you for coming back to me so quickly. Updaing my pubspec.yaml as mentioned above unfortunately did not resolve the issue.

**Comment by rainyl** [comment]
> @rainyl thank you for coming back to me so quickly. Updaing my pubspec.yaml as mentioned above unfortunately did not resolve the issue.

did you clean the previous build? flutter clean

**Comment by MichelM279** [comment]
That seems to be it, now it works after a flutter clean. Thank you very much.

**Comment by rainyl** [comment]
> That seems to be it, now it works after a flutter clean. Thank you very much.

😄
