### ISSUE TITLE
Build error when updating to version 1.4.3

### ISSUE THREAD

**Issue by redcurry** [rainyl/opencv_dart#375]
When I update the opencv_core version to 1.4.3 in pubspec.yaml, and I build my project to run on Windows, I get the following error (some file paths redacted):

```
opencv_core4120.lib(logtagconfigparser.obj) : error LNK2019: unresolved external symbol __std_find_first_of_trivial_pos_1 referenced in function "unsigned __int64 __cdecl std::_Find_first_of_pos_vectorized<char,char>(char const * const,unsigned __int64,char const * const,unsigned __int64)" (??$_Find_first_of_pos_vectorized@DD@std@@YA_KQEBD_K01@Z) [C:\(redacted)\build\windows\x64\_deps\libdartcv-build\dartcv\dartcv.vcxproj]
libprotobuf.lib(io_win32.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1 [C:\(redacted)\build\windows\x64\_deps\libdartcv-build\dartcv\dartcv.vcxproj]
C:\(redacted)\build\windows\x64\_deps\libdartcv-build\dartcv\Debug\dartcv.dll : fatal error LNK1120: 1 unresolved externals [C:\(redacted)\build\windows\x64\_deps\libdartcv-build\dartcv\dartcv.vcxproj]
Error: Build process failed.
```

If I go back to version 1.4.1 and rebuild, everything builds fine without error.

**Comment by rainyl** [comment]
@redcurry refer to https://github.com/rainyl/opencv_dart/discussions/371

TLDR: upgrade your visual studio.
